#!/bin/bash

#scroll
synclient VertScrollDelta=-58
synclient HorizScrollDelta=-58

#xrandr
xrandr --output HDMI-1 --above eDP-1 --auto
xrandr --output DP-2 --above eDP-1 --auto

#swip caps to esc
setxkbmap -option "caps:escape"
