#!/bin/bash

offset=900

WINID=`xdotool getactivewindow`
y=`xdotool getactivewindow | xargs xwininfo -id | grep "Absolute upper-left Y" | awk '{print $4}'`

if [ "$y" -ge "$offset" ]; then
    echo "move top"
    wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz
    xdotool windowmove $WINID 0 0
    wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
else
    echo "move bottom"
    wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz
    xdotool windowmove $WINID 0 $offset
    wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
fi
