#!/bin/bash

KEY="Android Studio"
PID=`wmctrl -pl | grep "$KEY" | head -n 1 | awk '{print $1}'`
FOCUS=`xdotool getactivewindow`

if [ -n "$PID" ]; then
    PID_INT=`printf %d $PID`
    if [ "$PID_INT" == "$FOCUS" ]; then
        xdotool windowminimize $FOCUS
    else
        xdotool windowactivate $PID_INT
    fi
else 
    /work/tools/android-studio/bin/studio.sh
fi
