#!/bin/bash

KEY="Genymotion"
PID=`wmctrl -pl | grep "$KEY" | head -n 1 | awk '{print $1}'`
FOCUS=`xdotool getactivewindow`
echo "PID="$PID
echo "FOCUS="$FOCUS

if [ -n "$PID" ]; then
    PID_INT=`printf %d $PID`
    echo "PID_INT"$PID_INT
    if [ "$PID_INT" == "$FOCUS" ]; then
        xdotool windowminimize $FOCUS
    else
        xdotool windowactivate $PID_INT
    fi
else 
    /work/tools/genymotion/player --vm-name "Google Nexus 5X - 7.0.0 - API 24 - 1080x1920"
fi
