#!/bin/bash

KEY="win7"
PID=`wmctrl -pl | grep "$KEY" | awk '{print $1}'`
FOCUS=`xdotool getactivewindow`
echo "PID="$PID
echo "FOCUS="$FOCUS

if [ -n "$PID" ]; then
    PID_INT=`printf %d $PID`
    echo "PID_INT"$PID_INT
    if [ "$PID_INT" == "$FOCUS" ]; then
        xdotool windowminimize $FOCUS
    else
        xdotool windowactivate $PID_INT
    fi
else 
    VBoxManage startvm "win7"
fi
