#!/bin/bash

KEY="simon_pc"
PID=`wmctrl -pl | grep "$KEY" | head -n 1 | awk '{print $1}'`
FOCUS=`xdotool getactivewindow`
echo "PID="$PID
echo "FOCUS="$FOCUS

if [ -n "$PID" ]; then
    PID_INT=`printf %d $PID`
    echo "PID_INT"$PID_INT
    if [ "$PID_INT" == "$FOCUS" ]; then
        xdotool windowminimize $FOCUS
    else
        xdotool windowactivate $PID_INT
    fi
else 
    /usr/bin/remmina -c /data/env/bin/simon_pc.remmina
fi
